var i18nStrings = {
  en: {
    "nav-home": "Home",
    "nav-about": "About",
    "nav-features": "Features",
    "nav-gallery": "Gallery",
    "nav-blog": "Blog",
    "nav-contact": "Contact",
    "nav-more": "More",
    "nav-join": "Join",
    "nav-login": "Login",
    "nav-logout": "Logout",
    "nav-logged-in-as": "Logged in as",
    "nav-services": "Services",
    "nav-products": "Products",
    "nav-pricing": "Pricing",
    "nav-team": "Team",
    "nav-careers": "Careers",
    "nav-privacy": "Privacy",
    "nav-profile": "Profile",
    "nav-messages": "Messages",
    "search-placeholder": "Search...",
    "lang-en-label": "English",
    "lang-bm-label": "Bahasa Melayu",
    "footer-privacy": "Privacy",
    "footer-contact": "Contact",
    "footer-team": "Team",
    "footer-sitemap": "Sitemap",
    "footer-facebook": "Facebook",
    "footer-instagram": "Instagram",
    "footer-pdpa": "PDPA Malaysia",
    "sitemap-title": "Sitemap",
    "sitemap-subtitle": "All pages on Fluxr",
    "sitemap-lead": "Quick links to every section of the Fluxr website.",
    "sitemap-sec-main": "Main Pages",
    "sitemap-sec-company": "Company",
    "sitemap-sec-account": "Account",
    "sitemap-sec-other": "Other",
    "sitemap-blog-post": "Blog Post",
    "notif-friend": "{name} added you as a friend",
    "notif-message": "{name} sent you a message",
    "notif-post": "{name} posted a new update",
    "notif-info": "{name} sent you a notification",
    "notif-empty": "No notifications yet.",
    "notif-login": "Login to see your notifications.",
    "hero-title": "Connect. Share. Fluxr.",
    "hero-lead": "The social network for posting updates, sharing photos and chatting with friends.",
    "alert-welcome": "<strong>Welcome to Fluxr.</strong> Sign up free and start connecting today.",
    "btn-get-started": "Get Started",
    "btn-about-fluxr": "About Fluxr",
    "home-why-title": "Why Fluxr?",
    "home-why-lead": "Everything you need to stay connected online.",
    "home-f1-title": "Posts & Feed",
    "home-f1-text": "Write updates and see what your friends posted today.",
    "home-f2-title": "Photo Albums",
    "home-f2-text": "Share photos with friends and browse public albums.",
    "home-f3-title": "Friends & Groups",
    "home-f3-text": "Add friends and join groups based on your interests.",
    "home-recent-posts": "Recent Posts",
    "home-video-title": "About Fluxr",
    "chat-btn": "Chat",
    "chat-support": "Fluxr Support",
    "chat-status": "Usually replies within a few hours",
    "chat-greeting": "Hi! Need help with your account, gallery or groups? Send us a message.",
    "chat-placeholder": "Write your message...",
    "chat-send": "Send",
    "chat-you": "You",
    "chat-reply": "Got it. Our team usually replies within a few hours on weekdays.",
    "profile-member": "Fluxr Member",
    "profile-guest": "Guest User",
    "profile-friends": "Friends",
    "profile-posts": "Posts",
    "profile-add-friend": "Add Friend",
    "profile-view-btn": "View Profile",
    "profile-page-title": "My Profile",
    "profile-page-sub": "Your Fluxr account",
    "profile-bio-label": "Bio",
    "profile-save-bio": "Save Bio",
    "profile-go-messages": "Go to Messages",
    "profile-friends-title": "My Friends",
    "profile-posts-title": "My Posts",
    "profile-no-bio": "No bio yet.",
    "profile-no-friends": "No friends yet. Add registered members below.",
    "profile-no-posts": "No posts yet. Write one on the home feed.",
    "profile-login-first": "Please login or register first.",
    "profile-msg-btn": "Message",
    "profile-suggest-title": "Registered Members",
    "profile-no-suggest": "No other registered members to add yet.",
    "profile-all-friends": "You already added all registered members.",
    "profile-register-more": "To add more people, logout first then register another account on Join page.",
    "msg-login-fail": "Account not found. Please register first.",
    "msg-email-exists": "This email is already registered.",
    "feed-write-label": "Write a post",
    "feed-post-btn": "Post",
    "feed-you-badge": "You",
    "feat-open-link": "Open feature \u2192",
    "msg-page-title": "Private Messages",
    "msg-page-sub": "Chat with your friends",
    "msg-friends-list": "Friends",
    "msg-pick-friend": "Pick a friend to start",
    "msg-empty": "Select a friend from the list.",
    "msg-placeholder": "Type your message...",
    "msg-chat-with": "Chat with",
    "msg-start": "No messages yet. Say hello!",
    "feed-empty": "No posts yet. Login and write the first post.",
    "search-none": "No Fluxr page found for:",
    "form-name": "Name",
    "form-email": "Email",
    "form-password": "Password",
    "form-subject": "Subject",
    "form-message": "Message",
    "form-fullname": "Full Name",
    "form-confirm-password": "Confirm Password",
    "form-dob": "Date of Birth",
    "form-gender": "Gender",
    "form-gender-male": "Male",
    "form-gender-female": "Female",
    "form-gender-other": "Other",
    "form-remember": "Remember me",
    "btn-send-message": "Send Message",
    "btn-sign-in": "Sign In",
    "btn-register": "Register",
    "btn-learn-more": "Learn More",
    "btn-apply": "Apply",
    "btn-read-more": "Read More",
    "btn-view-gallery": "View Gallery",
    "btn-see-features": "See Features",
    "btn-choose-plan": "Choose Plan",
    "btn-back-home": "Back to Home",
    "btn-back-blog": "Back to Blog",
    "about-title": "About Fluxr",
    "about-subtitle": "Learn about our company",
    "about-who": "Who We Are",
    "about-p1": "Fluxr is a social network company based in Malaysia. Our team builds tools for people to post updates, share photos and message friends online.",
    "about-p2": "The Fluxr platform includes profiles, a home feed, private messaging and photo galleries. Everything is designed to work on desktop and mobile.",
    "about-info-title": "Company Info",
    "about-co": "Company:",
    "about-founded": "Founded:",
    "about-office": "Head office:",
    "about-email-label": "Email:",
    "about-launched": "Website launched:",
    "about-updated": "Last updated:",
    "about-mission-t": "Mission",
    "about-mission-d": "Help people stay connected online through a simple and reliable social platform.",
    "about-vision-t": "Vision",
    "about-vision-d": "Become a trusted social network that people use every day to share and communicate.",
    "about-values-t": "Values",
    "about-values-d": "Keep it simple, respect privacy and make every page work on phone and laptop.",
    "about-video-title": "Intro Video",
    "feat-title": "Features",
    "feat-subtitle": "Everything Fluxr offers",
    "feat-lead": "Tools to connect, share and communicate online.",
    "feat-1-t": "User Profiles",
    "feat-1-d": "Add your photo and a short bio. Friends can view your profile from the member list.",
    "feat-2-t": "Home Feed",
    "feat-2-d": "Post text updates and see what your friends shared. New posts appear on the home page.",
    "feat-3-t": "Private Messages",
    "feat-3-d": "Send direct messages to friends. Each conversation stays in one thread.",
    "feat-4-t": "Photo Gallery",
    "feat-4-d": "Upload photos from events and open them full-size from the gallery page.",
    "contact-title": "Contact Us",
    "contact-subtitle": "We are here to help",
    "contact-send-title": "Send a Message",
    "contact-touch": "Get in Touch",
    "contact-hours": "Mon-Fri, 9am-5pm",
    "login-title": "Login",
    "login-subtitle": "Sign in to your account",
    "login-welcome": "Welcome back to Fluxr",
    "login-no-account": "No account yet?",
    "login-register-link": "Register here",
    "join-title": "Create Account",
    "join-subtitle": "Create your free account",
    "join-welcome": "Join Fluxr for free",
    "join-have-account": "Already have an account?",
    "join-login-link": "Login here",
    "gallery-title": "Photo Gallery",
    "gallery-subtitle": "Moments shared on Fluxr",
    "gallery-lead": "Photos from Fluxr events and community moments.",
    "gal-1": "Launch event 2026",
    "gal-2": "Team workshop",
    "gal-3": "Company sports day",
    "gal-4": "Team meeting",
    "gal-5": "Office opening",
    "gal-6": "Team outing",
    "blog-title": "Blog",
    "blog-subtitle": "News and updates from Fluxr",
    "blog-lead": "Latest news, product updates and community stories.",
    "blog-1-date": "12 June 2026",
    "blog-1-title": "Fluxr Platform Goes Live",
    "blog-1-text": "Our new website is online. Users can register, set up profiles and start posting today.",
    "blog-2-date": "5 June 2026",
    "blog-2-title": "Summer Meetup Photo Album",
    "blog-2-text": "Over 50 photos from our launch event are now in the gallery. Tag your friends and share.",
    "blog-3-date": "28 May 2026",
    "blog-3-title": "Mobile View Now Available",
    "blog-3-text": "Fluxr works better on phones. Try the feed, messages and gallery from your mobile browser.",
    "blogpost-title": "Fluxr Platform Goes Live",
    "blogpost-date": "Posted 12 June 2026 by Siti Aminah",
    "blogpost-p1": "After months of development, the Fluxr website is ready for the public. Users can sign up, create profiles, browse the gallery and post on the home feed.",
    "blogpost-p2": "Our development team focused on speed and ease of use. The site works on desktop and mobile, with pages for messaging, pricing and account settings.",
    "blogpost-p3": "We will roll out new features every month. Send your feedback to hello@fluxr.my or use the contact form on this site.",
    "services-title": "Our Services",
    "services-subtitle": "What we offer our users",
    "services-lead": "Support and tools to help you get the most from Fluxr.",
    "svc-1-t": "Profile Setup",
    "svc-1-d": "Help new users create profiles with photo and bio.",
    "svc-2-t": "Group Pages",
    "svc-2-d": "Set up pages for communities, brands and team groups.",
    "svc-3-t": "Event Listings",
    "svc-3-d": "Post company events with date, venue and RSVP count.",
    "svc-4-t": "Photo Hosting",
    "svc-4-d": "Store and display album photos for members.",
    "svc-5-t": "Account Support",
    "svc-5-d": "Reset passwords and fix login issues via email.",
    "svc-6-t": "Moderation",
    "svc-6-d": "Review reported posts and remove spam content.",
    "products-title": "Products",
    "products-subtitle": "Fluxr platform products",
    "products-lead": "Products built by Fluxr for everyday social networking.",
    "prod-1-t": "Fluxr Web App",
    "prod-1-d": "The main Fluxr site. Sign in from any browser on your laptop or phone.",
    "prod-2-t": "Fluxr Mobile View",
    "prod-2-d": "Same account, smaller screen. Feed, messages and gallery all fit on mobile.",
    "prod-3-t": "Group Admin Panel",
    "prod-3-d": "Club admins can approve members, pin posts and manage group photos.",
    "prod-4-t": "Fluxr for Business",
    "prod-4-d": "Brand pages with event listings, photo albums and member directories.",
    "pricing-title": "Pricing Plans",
    "pricing-subtitle": "Choose the plan that fits you",
    "pricing-lead": "Simple plans for every user. Upgrade anytime.",
    "pricing-monthly": "Monthly",
    "pricing-yearly": "Yearly (save 17%)",
    "pricing-yearly-short": "Yearly",
    "pricing-popular": "Popular",
    "pricing-per-month": "per month",
    "pricing-per-year": "per year",
    "plan-basic": "Basic",
    "plan-standard": "Standard",
    "plan-pro": "Pro",
    "plan-f-profile": "Profile page",
    "plan-f-friends50": "50 friends",
    "plan-f-photos10": "10 photo uploads",
    "plan-f-friends-unlimited": "Unlimited friends",
    "plan-f-photos100": "100 photo uploads",
    "plan-f-groups": "Group pages",
    "plan-f-all-standard": "All Standard features",
    "plan-f-support": "Priority support",
    "plan-f-themes": "Custom group themes",
    "team-title": "Our Team",
    "team-subtitle": "The people behind Fluxr",
    "team-lead": "Meet the Fluxr leadership and product team.",
    "team-role-1": "Chief Executive Officer",
    "team-role-2": "Head of Design",
    "team-role-3": "Lead Developer",
    "team-role-4": "Marketing Manager",
    "team-role-5": "Back-end Engineer",
    "team-role-6": "Customer Support Lead",
    "career-job-1": "Junior Web Developer",
    "career-job-2": "UI Designer",
    "career-job-3": "Community Moderator",
    "career-job-4": "Content Writer",
    "career-dept-1": "Engineering",
    "career-dept-2": "Design",
    "career-dept-3": "Operations",
    "career-dept-4": "Marketing",
    "career-loc-kl": "Kuala Lumpur",
    "careers-title": "Careers",
    "careers-subtitle": "Join the Fluxr team",
    "careers-lead": "Open roles at our Kuala Lumpur office and remote positions.",
    "careers-col-position": "Position",
    "careers-col-dept": "Department",
    "careers-col-location": "Location",
    "careers-col-type": "Type",
    "careers-remote": "Remote",
    "careers-internship": "Internship",
    "careers-parttime": "Part-time",
    "careers-contract": "Contract",
    "privacy-title": "Privacy Policy",
    "privacy-subtitle": "How Fluxr handles your data",
    "privacy-intro": "Fluxr Sdn Bhd respects your privacy. This page explains what we collect, how we use it and what you can control.",
    "privacy-updated": "Last updated: June 2026",
    "privacy-h1": "Information We Collect",
    "privacy-b1": "When you register on Fluxr, we collect your name, email address and profile details such as photo and bio. When you use the platform, we also store posts, messages and photos you upload to your feed and gallery.",
    "privacy-h2": "How We Use Data",
    "privacy-b2": "Your data is used to run Fluxr features including login, messaging, friend lists and the photo gallery. We use account information to personalise your profile and display your activity on the home feed. Fluxr does not sell personal information to third parties.",
    "privacy-h3": "Data Sharing",
    "privacy-b3": "We only share data when required by law or when you choose to make content public on your profile. Service providers who help us host the platform may process data on our behalf under strict confidentiality agreements.",
    "privacy-h4": "Account Control",
    "privacy-b4": "You can edit your profile details at any time from your account settings. To request account deletion or a copy of your data, contact us at privacy@fluxr.my. Passwords are stored using standard hashing methods and are never stored in plain text.",
    "privacy-h5": "Cookies & Security",
    "privacy-b5": "Fluxr uses cookies to keep you logged in and remember your preferences such as dark mode and language. We take reasonable steps to protect your data from unauthorised access, loss or misuse.",
    "privacy-h6": "Policy Updates",
    "privacy-b6": "We may update this policy from time to time. Changes will be posted on this page with a new date. For questions about privacy, email privacy@fluxr.my or visit our contact page.",
    "err-title": "Page Not Found",
    "err-text": "The page you are looking for does not exist or has been moved.",
    "msg-name-short": "Please enter your full name.",
    "msg-email-invalid": "Please enter a valid email address.",
    "msg-subject-short": "Subject must be at least 3 characters.",
    "msg-message-short": "Message must be at least 10 characters.",
    "msg-sent": "Message sent. We will get back to you soon.",
    "msg-login-email": "Invalid email format.",
    "msg-password-short": "Password must be at least 6 characters.",
    "msg-login-ok": "Login successful.",
    "msg-password-match": "Passwords do not match.",
    "msg-join-ok": "Account created. You can log in now."
  },
  bm: {
    "nav-home": "Laman Utama",
    "nav-about": "Tentang",
    "nav-features": "Ciri-ciri",
    "nav-gallery": "Galeri",
    "nav-blog": "Blog",
    "nav-contact": "Hubungi",
    "nav-more": "Lagi",
    "nav-join": "Daftar",
    "nav-login": "Log Masuk",
    "nav-logout": "Log Keluar",
    "nav-logged-in-as": "Log masuk sebagai",
    "nav-services": "Perkhidmatan",
    "nav-products": "Produk",
    "nav-pricing": "Harga",
    "nav-team": "Pasukan",
    "nav-careers": "Kerjaya",
    "nav-privacy": "Privasi",
    "nav-profile": "Profil",
    "nav-messages": "Mesej",
    "search-placeholder": "Cari...",
    "lang-en-label": "English",
    "lang-bm-label": "Bahasa Melayu",
    "footer-privacy": "Privasi",
    "footer-contact": "Hubungi",
    "footer-team": "Pasukan",
    "footer-sitemap": "Peta Laman",
    "footer-facebook": "Facebook",
    "footer-instagram": "Instagram",
    "footer-pdpa": "PDPA Malaysia",
    "sitemap-title": "Peta Laman",
    "sitemap-subtitle": "Semua halaman di Fluxr",
    "sitemap-lead": "Pautan pantas ke setiap bahagian laman web Fluxr.",
    "sitemap-sec-main": "Halaman Utama",
    "sitemap-sec-company": "Syarikat",
    "sitemap-sec-account": "Akaun",
    "sitemap-sec-other": "Lain-lain",
    "sitemap-blog-post": "Catatan Blog",
    "notif-friend": "{name} menambah anda sebagai rakan",
    "notif-message": "{name} menghantar mesej kepada anda",
    "notif-post": "{name} menyiarkan kemas kini baharu",
    "notif-info": "{name} menghantar pemberitahuan kepada anda",
    "notif-empty": "Tiada pemberitahuan lagi.",
    "notif-login": "Log masuk untuk lihat pemberitahuan anda.",
    "hero-title": "Berhubung. Kongsi. Fluxr.",
    "hero-lead": "Rangkaian sosial untuk siarkan kemas kini, kongsi foto dan sembang dengan rakan.",
    "alert-welcome": "<strong>Selamat datang ke Fluxr.</strong> Daftar percuma dan mula berhubung hari ini.",
    "btn-get-started": "Mula Sekarang",
    "btn-about-fluxr": "Tentang Fluxr",
    "home-why-title": "Mengapa Fluxr?",
    "home-why-lead": "Semua yang anda perlukan untuk kekal berhubung dalam talian.",
    "home-f1-title": "Siaran & Suapan",
    "home-f1-text": "Tulis kemas kini dan lihat apa yang rakan anda siarkan hari ini.",
    "home-f2-title": "Album Foto",
    "home-f2-text": "Kongsi foto dengan rakan dan layari album awam.",
    "home-f3-title": "Rakan & Kumpulan",
    "home-f3-text": "Tambah rakan dan sertai kumpulan mengikut minat anda.",
    "home-recent-posts": "Siaran Terkini",
    "home-video-title": "Tentang Fluxr",
    "chat-btn": "Sembang",
    "chat-support": "Sokongan Fluxr",
    "chat-status": "Biasanya membalas dalam beberapa jam",
    "chat-greeting": "Hai! Perlukan bantuan dengan akaun, galeri atau kumpulan? Hantar mesej kepada kami.",
    "chat-placeholder": "Tulis mesej anda...",
    "chat-send": "Hantar",
    "chat-you": "Anda",
    "chat-reply": "Baik. Pasukan kami biasanya membalas dalam beberapa jam pada hari bekerja.",
    "profile-member": "Ahli Fluxr",
    "profile-guest": "Pengguna Tetamu",
    "profile-friends": "Rakan",
    "profile-posts": "Siaran",
    "profile-add-friend": "Tambah Rakan",
    "profile-view-btn": "Lihat Profil",
    "profile-page-title": "Profil Saya",
    "profile-page-sub": "Akaun Fluxr anda",
    "profile-bio-label": "Bio",
    "profile-save-bio": "Simpan Bio",
    "profile-go-messages": "Ke Mesej",
    "profile-friends-title": "Rakan Saya",
    "profile-posts-title": "Siaran Saya",
    "profile-no-bio": "Tiada bio lagi.",
    "profile-no-friends": "Tiada rakan lagi. Tambah ahli berdaftar di bawah.",
    "profile-no-posts": "Tiada siaran lagi. Tulis di suapan utama.",
    "profile-login-first": "Sila log masuk atau daftar dahulu.",
    "profile-msg-btn": "Mesej",
    "profile-suggest-title": "Ahli Berdaftar",
    "profile-no-suggest": "Tiada ahli berdaftar lain untuk ditambah lagi.",
    "profile-all-friends": "Anda sudah menambah semua ahli berdaftar.",
    "profile-register-more": "Untuk tambah lebih ramai, log keluar dahulu kemudian daftar akaun lain di halaman Daftar.",
    "msg-login-fail": "Akaun tidak dijumpai. Sila daftar dahulu.",
    "msg-email-exists": "E-mel ini sudah didaftarkan.",
    "feed-write-label": "Tulis siaran",
    "feed-post-btn": "Siar",
    "feed-you-badge": "Anda",
    "feat-open-link": "Buka ciri \u2192",
    "msg-page-title": "Mesej Peribadi",
    "msg-page-sub": "Sembang dengan rakan anda",
    "msg-friends-list": "Rakan",
    "msg-pick-friend": "Pilih rakan untuk mula",
    "msg-empty": "Pilih rakan dari senarai.",
    "msg-placeholder": "Taip mesej anda...",
    "msg-chat-with": "Sembang dengan",
    "msg-start": "Tiada mesej lagi. Ucap hai!",
    "feed-empty": "Tiada siaran lagi. Log masuk dan tulis siaran pertama.",
    "search-none": "Tiada halaman Fluxr dijumpai untuk:",
    "form-name": "Nama",
    "form-email": "E-mel",
    "form-password": "Kata Laluan",
    "form-subject": "Subjek",
    "form-message": "Mesej",
    "form-fullname": "Nama Penuh",
    "form-confirm-password": "Sahkan Kata Laluan",
    "form-dob": "Tarikh Lahir",
    "form-gender": "Jantina",
    "form-gender-male": "Lelaki",
    "form-gender-female": "Perempuan",
    "form-gender-other": "Lain-lain",
    "form-remember": "Ingat saya",
    "btn-send-message": "Hantar Mesej",
    "btn-sign-in": "Log Masuk",
    "btn-register": "Daftar",
    "btn-learn-more": "Ketahui Lagi",
    "btn-apply": "Mohon",
    "btn-read-more": "Baca Lagi",
    "btn-view-gallery": "Lihat Galeri",
    "btn-see-features": "Lihat Ciri-ciri",
    "btn-choose-plan": "Pilih Pelan",
    "btn-back-home": "Kembali ke Laman Utama",
    "btn-back-blog": "Kembali ke Blog",
    "about-title": "Tentang Fluxr",
    "about-subtitle": "Ketahui tentang syarikat kami",
    "about-who": "Siapa Kami",
    "about-p1": "Fluxr ialah syarikat rangkaian sosial berpangkalan di Malaysia. Pasukan kami membina alat untuk orang ramai menyiarkan kemas kini, berkongsi foto dan menghantar mesej kepada rakan dalam talian.",
    "about-p2": "Platform Fluxr merangkumi profil, suapan utama, mesej peribadi dan galeri foto. Semuanya direka untuk desktop dan mudah alih.",
    "about-info-title": "Maklumat Syarikat",
    "about-co": "Syarikat:",
    "about-founded": "Ditubuhkan:",
    "about-office": "Pejabat utama:",
    "about-email-label": "E-mel:",
    "about-launched": "Laman web dilancarkan:",
    "about-updated": "Kemas kini terakhir:",
    "about-mission-t": "Misi",
    "about-mission-d": "Membantu orang ramai kekal berhubung dalam talian melalui platform sosial yang mudah dan boleh dipercayai.",
    "about-vision-t": "Visi",
    "about-vision-d": "Menjadi rangkaian sosial yang dipercayai dan digunakan setiap hari untuk berkongsi dan berkomunikasi.",
    "about-values-t": "Nilai",
    "about-values-d": "Kekalkan kesederhanaan, hormati privasi dan pastikan setiap halaman berfungsi pada telefon dan komputer riba.",
    "about-video-title": "Video Pengenalan",
    "feat-title": "Ciri-ciri",
    "feat-subtitle": "Semua yang Fluxr tawarkan",
    "feat-lead": "Alat untuk berhubung, berkongsi dan berkomunikasi dalam talian.",
    "feat-1-t": "Profil Pengguna",
    "feat-1-d": "Tambah foto dan bio ringkas. Rakan boleh lihat profil anda dari senarai ahli.",
    "feat-2-t": "Suapan Utama",
    "feat-2-d": "Siarkan kemas kini teks dan lihat apa yang dikongsi rakan. Siaran baharu muncul di laman utama.",
    "feat-3-t": "Mesej Peribadi",
    "feat-3-d": "Hantar mesej terus kepada rakan. Setiap perbualan kekal dalam satu urutan.",
    "feat-4-t": "Galeri Foto",
    "feat-4-d": "Muat naik foto dari acara dan buka saiz penuh dari halaman galeri.",
    "contact-title": "Hubungi Kami",
    "contact-subtitle": "Kami sedia membantu",
    "contact-send-title": "Hantar Mesej",
    "contact-touch": "Hubungi Kami",
    "contact-hours": "Isn-Jum, 9pg-5ptg",
    "login-title": "Log Masuk",
    "login-subtitle": "Log masuk ke akaun anda",
    "login-welcome": "Selamat kembali ke Fluxr",
    "login-no-account": "Belum ada akaun?",
    "login-register-link": "Daftar di sini",
    "join-title": "Cipta Akaun",
    "join-subtitle": "Cipta akaun percuma anda",
    "join-welcome": "Sertai Fluxr secara percuma",
    "join-have-account": "Sudah ada akaun?",
    "join-login-link": "Log masuk di sini",
    "gallery-title": "Galeri Foto",
    "gallery-subtitle": "Detik dikongsi di Fluxr",
    "gallery-lead": "Foto dari acara Fluxr dan detik komuniti.",
    "gal-1": "Acara pelancaran 2026",
    "gal-2": "Bengkel pasukan",
    "gal-3": "Hari sukan syarikat",
    "gal-4": "Mesyuarat pasukan",
    "gal-5": "Pembukaan pejabat",
    "gal-6": "Lawatan pasukan",
    "blog-title": "Blog",
    "blog-subtitle": "Berita dan kemas kini dari Fluxr",
    "blog-lead": "Berita terkini, kemas kini produk dan cerita komuniti.",
    "blog-1-date": "12 Jun 2026",
    "blog-1-title": "Platform Fluxr Dilancarkan",
    "blog-1-text": "Laman web baharu kami sudah dalam talian. Pengguna boleh mendaftar, sediakan profil dan mula menyiarkan hari ini.",
    "blog-2-date": "5 Jun 2026",
    "blog-2-title": "Album Foto Pertemuan Musim Panas",
    "blog-2-text": "Lebih 50 foto dari acara pelancaran kami kini dalam galeri. Tag rakan anda dan kongsi.",
    "blog-3-date": "28 Mei 2026",
    "blog-3-title": "Paparan Mudah Alih Kini Tersedia",
    "blog-3-text": "Fluxr berfungsi lebih baik pada telefon. Cuba suapan, mesej dan galeri dari pelayar mudah alih anda.",
    "blogpost-title": "Platform Fluxr Dilancarkan",
    "blogpost-date": "Disiarkan 12 Jun 2026 oleh Siti Aminah",
    "blogpost-p1": "Selepas berbulan-bulan pembangunan, laman web Fluxr sudah sedia untuk orang ramai. Pengguna boleh mendaftar, mencipta profil, melayari galeri dan menyiarkan di suapan utama.",
    "blogpost-p2": "Pasukan pembangunan kami memfokuskan kelajuan dan kemudahan penggunaan. Laman ini berfungsi pada desktop dan mudah alih, dengan halaman untuk mesej, harga dan tetapan akaun.",
    "blogpost-p3": "Kami akan melancarkan ciri baharu setiap bulan. Hantar maklum balas anda ke hello@fluxr.my atau gunakan borang hubungi di laman ini.",
    "services-title": "Perkhidmatan Kami",
    "services-subtitle": "Apa yang kami tawarkan kepada pengguna",
    "services-lead": "Sokongan dan alat untuk membantu anda mendapat manfaat maksimum dari Fluxr.",
    "svc-1-t": "Persediaan Profil",
    "svc-1-d": "Bantu pengguna baharu mencipta profil dengan foto dan bio.",
    "svc-2-t": "Halaman Kumpulan",
    "svc-2-d": "Sediakan halaman untuk komuniti, jenama dan kumpulan pasukan.",
    "svc-3-t": "Senarai Acara",
    "svc-3-d": "Siarkan acara syarikat dengan tarikh, tempat dan kiraan RSVP.",
    "svc-4-t": "Hos Foto",
    "svc-4-d": "Simpan dan paparkan foto album untuk ahli.",
    "svc-5-t": "Sokongan Akaun",
    "svc-5-d": "Tetapkan semula kata laluan dan selesaikan masalah log masuk melalui e-mel.",
    "svc-6-t": "Moderasi",
    "svc-6-d": "Semak siaran dilaporkan dan buang kandungan spam.",
    "products-title": "Produk",
    "products-subtitle": "Produk platform Fluxr",
    "products-lead": "Produk dibina oleh Fluxr untuk rangkaian sosial harian.",
    "prod-1-t": "Aplikasi Web Fluxr",
    "prod-1-d": "Laman utama Fluxr. Log masuk dari mana-mana pelayar pada komputer riba atau telefon anda.",
    "prod-2-t": "Paparan Mudah Alih Fluxr",
    "prod-2-d": "Akaun sama, skrin lebih kecil. Suapan, mesej dan galeri semuanya muat pada mudah alih.",
    "prod-3-t": "Panel Admin Kumpulan",
    "prod-3-d": "Admin kelab boleh luluskan ahli, pin siaran dan urus foto kumpulan.",
    "prod-4-t": "Fluxr untuk Perniagaan",
    "prod-4-d": "Halaman jenama dengan senarai acara, album foto dan direktori ahli.",
    "pricing-title": "Pelan Harga",
    "pricing-subtitle": "Pilih pelan yang sesuai untuk anda",
    "pricing-lead": "Pelan mudah untuk setiap pengguna. Naik taraf bila-bila masa.",
    "pricing-monthly": "Bulanan",
    "pricing-yearly": "Tahunan (jimat 17%)",
    "pricing-yearly-short": "Tahunan",
    "pricing-popular": "Popular",
    "pricing-per-month": "sebulan",
    "pricing-per-year": "setahun",
    "plan-basic": "Asas",
    "plan-standard": "Standard",
    "plan-pro": "Pro",
    "plan-f-profile": "Halaman profil",
    "plan-f-friends50": "50 rakan",
    "plan-f-photos10": "10 muat naik foto",
    "plan-f-friends-unlimited": "Rakan tanpa had",
    "plan-f-photos100": "100 muat naik foto",
    "plan-f-groups": "Halaman kumpulan",
    "plan-f-all-standard": "Semua ciri Standard",
    "plan-f-support": "Sokongan keutamaan",
    "plan-f-themes": "Tema kumpulan tersuai",
    "team-title": "Pasukan Kami",
    "team-subtitle": "Orang di sebalik Fluxr",
    "team-lead": "Kenali kepimpinan dan pasukan produk Fluxr.",
    "team-role-1": "Ketua Pegawai Eksekutif",
    "team-role-2": "Ketua Reka Bentuk",
    "team-role-3": "Ketua Pembangun",
    "team-role-4": "Pengurus Pemasaran",
    "team-role-5": "Jurutera Back-end",
    "team-role-6": "Ketua Sokongan Pelanggan",
    "career-job-1": "Pembangun Web Junior",
    "career-job-2": "Pereka UI",
    "career-job-3": "Penyederhana Komuniti",
    "career-job-4": "Penulis Kandungan",
    "career-dept-1": "Kejuruteraan",
    "career-dept-2": "Reka Bentuk",
    "career-dept-3": "Operasi",
    "career-dept-4": "Pemasaran",
    "career-loc-kl": "Kuala Lumpur",
    "careers-title": "Kerjaya",
    "careers-subtitle": "Sertai pasukan Fluxr",
    "careers-lead": "Jawatan kosong di pejabat Kuala Lumpur dan jawatan jarak jauh.",
    "careers-col-position": "Jawatan",
    "careers-col-dept": "Jabatan",
    "careers-col-location": "Lokasi",
    "careers-col-type": "Jenis",
    "careers-remote": "Jarak Jauh",
    "careers-internship": "Latihan Industri",
    "careers-parttime": "Separuh Masa",
    "careers-contract": "Kontrak",
    "privacy-title": "Dasar Privasi",
    "privacy-subtitle": "Bagaimana Fluxr mengendalikan data anda",
    "privacy-intro": "Fluxr Sdn Bhd menghormati privasi anda. Halaman ini menerangkan apa yang kami kumpul, bagaimana kami menggunakannya dan apa yang anda boleh kawal.",
    "privacy-updated": "Kemas kini terakhir: Jun 2026",
    "privacy-h1": "Maklumat Yang Kami Kumpul",
    "privacy-b1": "Apabila anda mendaftar di Fluxr, kami mengumpul nama, alamat e-mel dan butiran profil seperti foto dan bio. Apabila anda menggunakan platform, kami juga menyimpan siaran, mesej dan foto yang anda muat naik ke suapan dan galeri.",
    "privacy-h2": "Bagaimana Kami Gunakan Data",
    "privacy-b2": "Data anda digunakan untuk menjalankan ciri Fluxr termasuk log masuk, mesej, senarai rakan dan galeri foto. Kami menggunakan maklumat akaun untuk memperibadikan profil anda dan memaparkan aktiviti anda di suapan utama. Fluxr tidak menjual maklumat peribadi kepada pihak ketiga.",
    "privacy-h3": "Perkongsian Data",
    "privacy-b3": "Kami hanya berkongsi data apabila dikehendaki oleh undang-undang atau apabila anda memilih untuk menjadikan kandungan awam pada profil anda. Pembekal perkhidmatan yang membantu kami mengehos platform boleh memproses data bagi pihak kami di bawah perjanjian kerahsiaan yang ketat.",
    "privacy-h4": "Kawalan Akaun",
    "privacy-b4": "Anda boleh mengedit butiran profil anda pada bila-bila masa dari tetapan akaun. Untuk meminta pemadaman akaun atau salinan data anda, hubungi kami di privacy@fluxr.my. Kata laluan disimpan menggunakan kaedah hashing standard dan tidak pernah disimpan dalam teks biasa.",
    "privacy-h5": "Kuki & Keselamatan",
    "privacy-b5": "Fluxr menggunakan kuki untuk memastikan anda kekal log masuk dan mengingati pilihan anda seperti mod gelap dan bahasa. Kami mengambil langkah munasabah untuk melindungi data anda daripada akses tanpa kebenaran, kehilangan atau penyalahgunaan.",
    "privacy-h6": "Kemas Kini Dasar",
    "privacy-b6": "Kami boleh mengemas kini dasar ini dari semasa ke semasa. Perubahan akan disiarkan di halaman ini dengan tarikh baharu. Untuk soalan privasi, e-mel privacy@fluxr.my atau lawati halaman hubungi kami.",
    "err-title": "Halaman Tidak Dijumpai",
    "err-text": "Halaman yang anda cari tidak wujud atau telah dipindahkan.",
    "msg-name-short": "Sila masukkan nama penuh anda.",
    "msg-email-invalid": "Sila masukkan alamat e-mel yang sah.",
    "msg-subject-short": "Subjek mestilah sekurang-kurangnya 3 aksara.",
    "msg-message-short": "Mesej mestilah sekurang-kurangnya 10 aksara.",
    "msg-sent": "Mesej dihantar. Kami akan menghubungi anda tidak lama lagi.",
    "msg-login-email": "Format e-mel tidak sah.",
    "msg-password-short": "Kata laluan mestilah sekurang-kurangnya 6 aksara.",
    "msg-login-ok": "Log masuk berjaya.",
    "msg-password-match": "Kata laluan tidak sepadan.",
    "msg-join-ok": "Akaun dicipta. Anda boleh log masuk sekarang."
  }
};

function getFluxrLang() {
  return localStorage.getItem("fluxr-lang") || "en";
}

function fluxrT(key) {
  var lang = getFluxrLang();
  var pack = i18nStrings[lang] || i18nStrings.en;
  return pack[key] || i18nStrings.en[key] || key;
}

function applyLanguage(lang) {
  var pack = i18nStrings[lang] || i18nStrings.en;
  document.documentElement.lang = lang === "bm" ? "ms" : "en";

  document.querySelectorAll("[data-i18n]").forEach(function (el) {
    var key = el.getAttribute("data-i18n");
    if (pack[key]) {
      el.textContent = pack[key];
    }
  });

  document.querySelectorAll("[data-i18n-html]").forEach(function (el) {
    var key = el.getAttribute("data-i18n-html");
    if (pack[key]) {
      el.innerHTML = pack[key];
    }
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
    var key = el.getAttribute("data-i18n-placeholder");
    if (pack[key]) {
      el.setAttribute("placeholder", pack[key]);
    }
  });

  document.querySelectorAll("[data-i18n-aria]").forEach(function (el) {
    var key = el.getAttribute("data-i18n-aria");
    if (pack[key]) {
      el.setAttribute("aria-label", pack[key]);
    }
  });

  var langBtn = document.getElementById("langBtn");
  if (langBtn) {
    langBtn.textContent = lang === "bm" ? "BM" : "EN";
  }

  localStorage.setItem("fluxr-lang", lang);
  document.dispatchEvent(new CustomEvent("fluxr-lang-change", { detail: { lang: lang } }));
}

document.addEventListener("DOMContentLoaded", function () {
  applyLanguage(getFluxrLang());

  document.querySelectorAll(".lang-option").forEach(function (link) {
    link.addEventListener("click", function (e) {
      e.preventDefault();
      applyLanguage(link.getAttribute("data-lang"));
    });
  });
});
